module.exports = {
    base: "https://lewds.fun/api/v1/nsfw/",
	fun: "https://lewds.fun/api/v1/fun/",
    endpoints: {
        ass: "https://lewds.fun/api/v1/nsfw/ass",
        futa: "https://lewds.fun/api/v1/nsfw/futa",
        furgif: "https://lewds.fun/api/v1/nsfw/furgif",
	furfuta: "https://lewds.fun/api/v1/nsfw/furfuta",
        boobs: "https://lewds.fun/api/v1/nsfw/boobs",
        athighs: "https://lewds.fun/api/v1/nsfw/athighs",
        feet: "https://lewds.fun/api/v1/nsfw/feet",
        gifs: "https://lewds.fun/api/v1/nsfw/gifs",
	hboobs: "https://lewds.fun/api/v1/nsfw/hboobs",
	hentai: "https://lewds.fun/api/v1/nsfw/hentai",
	kink: "https://lewds.fun/api/v1/nsfw/kink",
	thighs: "https://lewds.fun/api/v1/nsfw/thighs",
	yuri: "https://lewds.fun/api/v1/nsfw/yuri",
	milk: "https://lewds.fun/api/v1/nsfw/milk",		
	slime: "https://lewds.fun/api/v1/nsfw/slime",
	trap: "https://lewds.fun/api/v1/nsfw/trap",
	kiss: "https://lewds.fun/api/v1/sfw/kiss",
	pantsu: "https://lewds.fun/api/v1/nsfw/pantsu",
	chat: ""https://lewds.fun/api/v1/fun/chat",
    }
}
